language: ruby
rvm:
- 2.6.4
services:
  - postgresql
before_script:
  - psql -c 'create database cardMaestro_test;' -U postgres ; bundle exec rake db:create && bundle exec rake db:migrate RAILS_ENV=test
